name: SimpleMyPoints
version: 0.0.3
main: net.jp.minecraft.plugin.SimpleMyPoints
commands:
    points:
        description: Simple my Points.
        usage: /points
        permission: smp.command
        permission-message: You don't have permission (smp.command)
    smp:
        description: Simple My Points.
        usage: /smp
        permission: smp.command
        permission-message: You don't have permission (smp.command)
    warp:
        description: Simple My Points.
        usage: /warp <PointName>
        permission: smp.warp
        permission-message: You don't have permission (smp.warp)
permissions:
    smp.*:
        description: Simple My Points.
        default: op

